import type { TrackingType } from './types';

export interface CatalogEntry {
  name: string;
  trackingType: TrackingType;
  defaultSets: number;
  category: 'Calisthenics' | 'Weighted Training' | 'Cardio' | 'Stretching' | 'Yoga';
}

export const EXERCISE_CATALOG: CatalogEntry[] = [
  // ── Calisthenics ──────────────────────────────────────────────────────────
  { name: 'Push-ups',               trackingType: 'bodyweight_reps', defaultSets: 3, category: 'Calisthenics' },
  { name: 'Wide Push-ups',          trackingType: 'bodyweight_reps', defaultSets: 3, category: 'Calisthenics' },
  { name: 'Diamond Push-ups',       trackingType: 'bodyweight_reps', defaultSets: 3, category: 'Calisthenics' },
  { name: 'Pike Push-ups',          trackingType: 'bodyweight_reps', defaultSets: 3, category: 'Calisthenics' },
  { name: 'Archer Push-ups',        trackingType: 'bodyweight_reps', defaultSets: 3, category: 'Calisthenics' },
  { name: 'Pull-ups',               trackingType: 'bodyweight_reps', defaultSets: 3, category: 'Calisthenics' },
  { name: 'Chin-ups',               trackingType: 'bodyweight_reps', defaultSets: 3, category: 'Calisthenics' },
  { name: 'Neutral Grip Pull-ups',  trackingType: 'bodyweight_reps', defaultSets: 3, category: 'Calisthenics' },
  { name: 'Muscle-ups',             trackingType: 'bodyweight_reps', defaultSets: 3, category: 'Calisthenics' },
  { name: 'Dips',                   trackingType: 'bodyweight_reps', defaultSets: 3, category: 'Calisthenics' },
  { name: 'Ring Rows',              trackingType: 'bodyweight_reps', defaultSets: 3, category: 'Calisthenics' },
  { name: 'Australian Pull-ups',    trackingType: 'bodyweight_reps', defaultSets: 3, category: 'Calisthenics' },
  { name: 'Bodyweight Squats',      trackingType: 'bodyweight_reps', defaultSets: 3, category: 'Calisthenics' },
  { name: 'Jump Squats',            trackingType: 'bodyweight_reps', defaultSets: 3, category: 'Calisthenics' },
  { name: 'Bulgarian Split Squats', trackingType: 'bodyweight_reps', defaultSets: 3, category: 'Calisthenics' },
  { name: 'Pistol Squats',          trackingType: 'bodyweight_reps', defaultSets: 3, category: 'Calisthenics' },
  { name: 'Lunges',                 trackingType: 'bodyweight_reps', defaultSets: 3, category: 'Calisthenics' },
  { name: 'Reverse Lunges',         trackingType: 'bodyweight_reps', defaultSets: 3, category: 'Calisthenics' },
  { name: 'Step-ups',               trackingType: 'bodyweight_reps', defaultSets: 3, category: 'Calisthenics' },
  { name: 'Glute Bridges',          trackingType: 'bodyweight_reps', defaultSets: 3, category: 'Calisthenics' },
  { name: 'Hip Thrusts',            trackingType: 'bodyweight_reps', defaultSets: 3, category: 'Calisthenics' },
  { name: 'Burpees',                trackingType: 'bodyweight_reps', defaultSets: 3, category: 'Calisthenics' },
  { name: 'Mountain Climbers',      trackingType: 'bodyweight_reps', defaultSets: 3, category: 'Calisthenics' },
  { name: 'Sit-ups',                trackingType: 'bodyweight_reps', defaultSets: 3, category: 'Calisthenics' },
  { name: 'Crunches',               trackingType: 'bodyweight_reps', defaultSets: 3, category: 'Calisthenics' },
  { name: 'Bicycle Crunches',       trackingType: 'bodyweight_reps', defaultSets: 3, category: 'Calisthenics' },
  { name: 'Leg Raises',             trackingType: 'bodyweight_reps', defaultSets: 3, category: 'Calisthenics' },
  { name: 'Hanging Leg Raises',     trackingType: 'bodyweight_reps', defaultSets: 3, category: 'Calisthenics' },
  { name: 'V-ups',                  trackingType: 'bodyweight_reps', defaultSets: 3, category: 'Calisthenics' },
  { name: 'Superman',               trackingType: 'bodyweight_reps', defaultSets: 3, category: 'Calisthenics' },
  { name: 'Plank',                  trackingType: 'duration',        defaultSets: 3, category: 'Calisthenics' },
  { name: 'Side Plank',             trackingType: 'duration',        defaultSets: 3, category: 'Calisthenics' },
  { name: 'Hollow Hold',            trackingType: 'duration',        defaultSets: 3, category: 'Calisthenics' },
  { name: 'L-sit',                  trackingType: 'duration',        defaultSets: 3, category: 'Calisthenics' },
  { name: 'Wall Sit',               trackingType: 'duration',        defaultSets: 3, category: 'Calisthenics' },
  { name: 'Handstand Hold',         trackingType: 'duration',        defaultSets: 3, category: 'Calisthenics' },
  { name: 'Handstand Push-ups',     trackingType: 'bodyweight_reps', defaultSets: 3, category: 'Calisthenics' },
  { name: 'Box Jumps',              trackingType: 'bodyweight_reps', defaultSets: 3, category: 'Calisthenics' },
  { name: 'Jump Rope',              trackingType: 'duration',        defaultSets: 3, category: 'Calisthenics' },

  // ── Weighted Training ────────────────────────────────────────────────────
  { name: 'Bench Press',            trackingType: 'reps_weight', defaultSets: 4, category: 'Weighted Training' },
  { name: 'Incline Bench Press',    trackingType: 'reps_weight', defaultSets: 4, category: 'Weighted Training' },
  { name: 'Decline Bench Press',    trackingType: 'reps_weight', defaultSets: 3, category: 'Weighted Training' },
  { name: 'Dumbbell Bench Press',   trackingType: 'reps_weight', defaultSets: 4, category: 'Weighted Training' },
  { name: 'Dumbbell Fly',           trackingType: 'reps_weight', defaultSets: 3, category: 'Weighted Training' },
  { name: 'Cable Fly',              trackingType: 'reps_weight', defaultSets: 3, category: 'Weighted Training' },
  { name: 'Overhead Press',         trackingType: 'reps_weight', defaultSets: 4, category: 'Weighted Training' },
  { name: 'Arnold Press',           trackingType: 'reps_weight', defaultSets: 3, category: 'Weighted Training' },
  { name: 'Lateral Raises',         trackingType: 'reps_weight', defaultSets: 3, category: 'Weighted Training' },
  { name: 'Front Raises',           trackingType: 'reps_weight', defaultSets: 3, category: 'Weighted Training' },
  { name: 'Face Pulls',             trackingType: 'reps_weight', defaultSets: 3, category: 'Weighted Training' },
  { name: 'Rear Delt Fly',          trackingType: 'reps_weight', defaultSets: 3, category: 'Weighted Training' },
  { name: 'Barbell Row',            trackingType: 'reps_weight', defaultSets: 4, category: 'Weighted Training' },
  { name: 'Dumbbell Row',           trackingType: 'reps_weight', defaultSets: 3, category: 'Weighted Training' },
  { name: 'Cable Row',              trackingType: 'reps_weight', defaultSets: 3, category: 'Weighted Training' },
  { name: 'Lat Pulldown',           trackingType: 'reps_weight', defaultSets: 4, category: 'Weighted Training' },
  { name: 'Deadlift',               trackingType: 'reps_weight', defaultSets: 4, category: 'Weighted Training' },
  { name: 'Romanian Deadlift',      trackingType: 'reps_weight', defaultSets: 3, category: 'Weighted Training' },
  { name: 'Sumo Deadlift',          trackingType: 'reps_weight', defaultSets: 3, category: 'Weighted Training' },
  { name: 'Barbell Squat',          trackingType: 'reps_weight', defaultSets: 4, category: 'Weighted Training' },
  { name: 'Front Squat',            trackingType: 'reps_weight', defaultSets: 3, category: 'Weighted Training' },
  { name: 'Goblet Squat',           trackingType: 'reps_weight', defaultSets: 3, category: 'Weighted Training' },
  { name: 'Leg Press',              trackingType: 'reps_weight', defaultSets: 4, category: 'Weighted Training' },
  { name: 'Leg Curl',               trackingType: 'reps_weight', defaultSets: 3, category: 'Weighted Training' },
  { name: 'Leg Extension',          trackingType: 'reps_weight', defaultSets: 3, category: 'Weighted Training' },
  { name: 'Calf Raises',            trackingType: 'reps_weight', defaultSets: 3, category: 'Weighted Training' },
  { name: 'Hip Thrust (Barbell)',   trackingType: 'reps_weight', defaultSets: 3, category: 'Weighted Training' },
  { name: 'Bicep Curl',             trackingType: 'reps_weight', defaultSets: 3, category: 'Weighted Training' },
  { name: 'Hammer Curl',            trackingType: 'reps_weight', defaultSets: 3, category: 'Weighted Training' },
  { name: 'Preacher Curl',          trackingType: 'reps_weight', defaultSets: 3, category: 'Weighted Training' },
  { name: 'Tricep Pushdown',        trackingType: 'reps_weight', defaultSets: 3, category: 'Weighted Training' },
  { name: 'Skull Crushers',         trackingType: 'reps_weight', defaultSets: 3, category: 'Weighted Training' },
  { name: 'Overhead Tricep Extension', trackingType: 'reps_weight', defaultSets: 3, category: 'Weighted Training' },
  { name: 'Close-grip Bench Press', trackingType: 'reps_weight', defaultSets: 3, category: 'Weighted Training' },
  { name: 'Good Mornings',          trackingType: 'reps_weight', defaultSets: 3, category: 'Weighted Training' },
  { name: 'Clean and Press',        trackingType: 'reps_weight', defaultSets: 3, category: 'Weighted Training' },
  { name: 'Power Clean',            trackingType: 'reps_weight', defaultSets: 3, category: 'Weighted Training' },
  { name: 'Kettlebell Swing',       trackingType: 'reps_weight', defaultSets: 3, category: 'Weighted Training' },
  { name: 'Kettlebell Press',       trackingType: 'reps_weight', defaultSets: 3, category: 'Weighted Training' },
  { name: 'Shrugs',                 trackingType: 'reps_weight', defaultSets: 3, category: 'Weighted Training' },
  { name: 'Upright Row',            trackingType: 'reps_weight', defaultSets: 3, category: 'Weighted Training' },
  { name: 'Hack Squat',             trackingType: 'reps_weight', defaultSets: 3, category: 'Weighted Training' },
  { name: 'T-bar Row',              trackingType: 'reps_weight', defaultSets: 3, category: 'Weighted Training' },
  { name: 'Chest-supported Row',    trackingType: 'reps_weight', defaultSets: 3, category: 'Weighted Training' },

  // ── Cardio ────────────────────────────────────────────────────────────────
  { name: 'Running',         trackingType: 'distance_time', defaultSets: 1, category: 'Cardio' },
  { name: 'Walking',         trackingType: 'distance_time', defaultSets: 1, category: 'Cardio' },
  { name: 'Cycling',         trackingType: 'distance_time', defaultSets: 1, category: 'Cardio' },
  { name: 'Rowing',          trackingType: 'distance_time', defaultSets: 1, category: 'Cardio' },
  { name: 'Swimming',        trackingType: 'distance_time', defaultSets: 1, category: 'Cardio' },
  { name: 'Sprints',         trackingType: 'distance_time', defaultSets: 6, category: 'Cardio' },
  { name: 'Stair Climber',   trackingType: 'duration',      defaultSets: 1, category: 'Cardio' },
  { name: 'Elliptical',      trackingType: 'duration',      defaultSets: 1, category: 'Cardio' },
  { name: 'HIIT',            trackingType: 'duration',      defaultSets: 1, category: 'Cardio' },
  { name: 'Jump Rope (Cardio)', trackingType: 'duration',   defaultSets: 3, category: 'Cardio' },

  // ── Stretching ────────────────────────────────────────────────────────────
  { name: 'Hip Flexor Stretch',   trackingType: 'duration', defaultSets: 2, category: 'Stretching' },
  { name: 'Hamstring Stretch',    trackingType: 'duration', defaultSets: 2, category: 'Stretching' },
  { name: 'Quad Stretch',         trackingType: 'duration', defaultSets: 2, category: 'Stretching' },
  { name: 'Calf Stretch',         trackingType: 'duration', defaultSets: 2, category: 'Stretching' },
  { name: 'Shoulder Stretch',     trackingType: 'duration', defaultSets: 2, category: 'Stretching' },
  { name: 'Chest Opener',         trackingType: 'duration', defaultSets: 2, category: 'Stretching' },
  { name: 'Spinal Twist',         trackingType: 'duration', defaultSets: 2, category: 'Stretching' },
  { name: 'Figure Four Stretch',  trackingType: 'duration', defaultSets: 2, category: 'Stretching' },
  { name: 'Pigeon Pose',          trackingType: 'duration', defaultSets: 2, category: 'Stretching' },
  { name: 'Cobra Stretch',        trackingType: 'duration', defaultSets: 2, category: 'Stretching' },
  { name: 'Cat-Cow',              trackingType: 'duration', defaultSets: 2, category: 'Stretching' },
  { name: 'Child\'s Pose',        trackingType: 'duration', defaultSets: 1, category: 'Stretching' },
  { name: 'Seated Forward Fold',  trackingType: 'duration', defaultSets: 2, category: 'Stretching' },
  { name: 'Standing Forward Fold',trackingType: 'duration', defaultSets: 2, category: 'Stretching' },
  { name: 'Neck Stretch',         trackingType: 'duration', defaultSets: 2, category: 'Stretching' },
  { name: 'IT Band Stretch',      trackingType: 'duration', defaultSets: 2, category: 'Stretching' },

  // ── Yoga ─────────────────────────────────────────────────────────────────
  { name: 'Sun Salutation',    trackingType: 'duration', defaultSets: 1, category: 'Yoga' },
  { name: 'Warrior I',         trackingType: 'duration', defaultSets: 2, category: 'Yoga' },
  { name: 'Warrior II',        trackingType: 'duration', defaultSets: 2, category: 'Yoga' },
  { name: 'Warrior III',       trackingType: 'duration', defaultSets: 2, category: 'Yoga' },
  { name: 'Downward Dog',      trackingType: 'duration', defaultSets: 2, category: 'Yoga' },
  { name: 'Tree Pose',         trackingType: 'duration', defaultSets: 2, category: 'Yoga' },
  { name: 'Triangle Pose',     trackingType: 'duration', defaultSets: 2, category: 'Yoga' },
  { name: 'Bridge Pose',       trackingType: 'duration', defaultSets: 2, category: 'Yoga' },
  { name: 'Wheel Pose',        trackingType: 'duration', defaultSets: 2, category: 'Yoga' },
  { name: 'Boat Pose',         trackingType: 'duration', defaultSets: 3, category: 'Yoga' },
  { name: 'Crow Pose',         trackingType: 'duration', defaultSets: 3, category: 'Yoga' },
  { name: 'Headstand',         trackingType: 'duration', defaultSets: 3, category: 'Yoga' },
  { name: 'Shoulder Stand',    trackingType: 'duration', defaultSets: 2, category: 'Yoga' },
  { name: 'Corpse Pose',       trackingType: 'duration', defaultSets: 1, category: 'Yoga' },
];

export function searchCatalog(query: string): CatalogEntry[] {
  if (!query.trim()) return [];
  const q = query.toLowerCase();
  return EXERCISE_CATALOG.filter((e) => e.name.toLowerCase().includes(q));
}
